[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "modelado-financiero"
version = "0.1.0"
description = "Librería de Finanzas Cuantitativas para valoración de derivados, volatilidad implícita y gestión de riesgo."
readme = "README.md"
requires-python = ">=3.11"

authors = [
    {name = "Jerson"},
    {name = "Comunidad ESFM"}
]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "networkx"
]

[tool.setuptools.packages.find]
include = ["modelado_financiero*"]